// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.21.12
// source: task_status.proto

package task

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskStatus int32

const (
	TaskStatus_CREATED TaskStatus = 0 //已创建
	TaskStatus_RUNNING TaskStatus = 1 //运行中
	TaskStatus_STOPPED TaskStatus = 2 //已停止
	TaskStatus_FAILED  TaskStatus = 3 //失败
	TaskStatus_SUCCESS TaskStatus = 4 //成功
)

// Enum value maps for TaskStatus.
var (
	TaskStatus_name = map[int32]string{
		0: "CREATED",
		1: "RUNNING",
		2: "STOPPED",
		3: "FAILED",
		4: "SUCCESS",
	}
	TaskStatus_value = map[string]int32{
		"CREATED": 0,
		"RUNNING": 1,
		"STOPPED": 2,
		"FAILED":  3,
		"SUCCESS": 4,
	}
)

func (x TaskStatus) Enum() *TaskStatus {
	p := new(TaskStatus)
	*p = x
	return p
}

func (x TaskStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_task_status_proto_enumTypes[0].Descriptor()
}

func (TaskStatus) Type() protoreflect.EnumType {
	return &file_task_status_proto_enumTypes[0]
}

func (x TaskStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskStatus.Descriptor instead.
func (TaskStatus) EnumDescriptor() ([]byte, []int) {
	return file_task_status_proto_rawDescGZIP(), []int{0}
}

type TaskStatusNoComment int32

const (
	TaskStatusNoComment_TSN_CREATED TaskStatusNoComment = 0
	TaskStatusNoComment_TSN_RUNNING TaskStatusNoComment = 1
	TaskStatusNoComment_TSN_STOPPED TaskStatusNoComment = 2
	TaskStatusNoComment_TSN_FAILED  TaskStatusNoComment = 3
	TaskStatusNoComment_TSN_SUCCESS TaskStatusNoComment = 4
)

// Enum value maps for TaskStatusNoComment.
var (
	TaskStatusNoComment_name = map[int32]string{
		0: "TSN_CREATED",
		1: "TSN_RUNNING",
		2: "TSN_STOPPED",
		3: "TSN_FAILED",
		4: "TSN_SUCCESS",
	}
	TaskStatusNoComment_value = map[string]int32{
		"TSN_CREATED": 0,
		"TSN_RUNNING": 1,
		"TSN_STOPPED": 2,
		"TSN_FAILED":  3,
		"TSN_SUCCESS": 4,
	}
)

func (x TaskStatusNoComment) Enum() *TaskStatusNoComment {
	p := new(TaskStatusNoComment)
	*p = x
	return p
}

func (x TaskStatusNoComment) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskStatusNoComment) Descriptor() protoreflect.EnumDescriptor {
	return file_task_status_proto_enumTypes[1].Descriptor()
}

func (TaskStatusNoComment) Type() protoreflect.EnumType {
	return &file_task_status_proto_enumTypes[1]
}

func (x TaskStatusNoComment) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskStatusNoComment.Descriptor instead.
func (TaskStatusNoComment) EnumDescriptor() ([]byte, []int) {
	return file_task_status_proto_rawDescGZIP(), []int{1}
}

var File_task_status_proto protoreflect.FileDescriptor

var file_task_status_proto_rawDesc = []byte{
	0x0a, 0x11, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2a, 0x4c, 0x0a, 0x0a, 0x54, 0x61, 0x73, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x0b, 0x0a, 0x07, 0x43, 0x52, 0x45, 0x41, 0x54, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0b,
	0x0a, 0x07, 0x52, 0x55, 0x4e, 0x4e, 0x49, 0x4e, 0x47, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x53,
	0x54, 0x4f, 0x50, 0x50, 0x45, 0x44, 0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06, 0x46, 0x41, 0x49, 0x4c,
	0x45, 0x44, 0x10, 0x03, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x55, 0x43, 0x43, 0x45, 0x53, 0x53, 0x10,
	0x04, 0x2a, 0x69, 0x0a, 0x13, 0x54, 0x61, 0x73, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x4e,
	0x6f, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x0f, 0x0a, 0x0b, 0x54, 0x53, 0x4e, 0x5f,
	0x43, 0x52, 0x45, 0x41, 0x54, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x54, 0x53, 0x4e,
	0x5f, 0x52, 0x55, 0x4e, 0x4e, 0x49, 0x4e, 0x47, 0x10, 0x01, 0x12, 0x0f, 0x0a, 0x0b, 0x54, 0x53,
	0x4e, 0x5f, 0x53, 0x54, 0x4f, 0x50, 0x50, 0x45, 0x44, 0x10, 0x02, 0x12, 0x0e, 0x0a, 0x0a, 0x54,
	0x53, 0x4e, 0x5f, 0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x10, 0x03, 0x12, 0x0f, 0x0a, 0x0b, 0x54,
	0x53, 0x4e, 0x5f, 0x53, 0x55, 0x43, 0x43, 0x45, 0x53, 0x53, 0x10, 0x04, 0x42, 0x13, 0x5a, 0x11,
	0x79, 0x61, 0x6e, 0x67, 0x79, 0x61, 0x6e, 0x67, 0x35, 0x32, 0x31, 0x34, 0x2f, 0x74, 0x61, 0x73,
	0x6b, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_task_status_proto_rawDescOnce sync.Once
	file_task_status_proto_rawDescData = file_task_status_proto_rawDesc
)

func file_task_status_proto_rawDescGZIP() []byte {
	file_task_status_proto_rawDescOnce.Do(func() {
		file_task_status_proto_rawDescData = protoimpl.X.CompressGZIP(file_task_status_proto_rawDescData)
	})
	return file_task_status_proto_rawDescData
}

var file_task_status_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_task_status_proto_goTypes = []interface{}{
	(TaskStatus)(0),          // 0: TaskStatus
	(TaskStatusNoComment)(0), // 1: TaskStatusNoComment
}
var file_task_status_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_task_status_proto_init() }
func file_task_status_proto_init() {
	if File_task_status_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_task_status_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_task_status_proto_goTypes,
		DependencyIndexes: file_task_status_proto_depIdxs,
		EnumInfos:         file_task_status_proto_enumTypes,
	}.Build()
	File_task_status_proto = out.File
	file_task_status_proto_rawDesc = nil
	file_task_status_proto_goTypes = nil
	file_task_status_proto_depIdxs = nil
}
