// Code generated by protoc-gen-enum-desc. DO NOT EDIT.
// versions:
// - protoc             v3.21.12
// source: task_status.proto

package task

var (
	TaskStatus_desc = map[TaskStatus]string{
		TaskStatus_CREATED: "已创建",
		TaskStatus_RUNNING: "运行中",
		TaskStatus_STOPPED: "已停止",
		TaskStatus_FAILED:  "失败",
		TaskStatus_SUCCESS: "成功",
	}
)

func (x TaskStatus) Desc() string {
	return TaskStatus_desc[x]
}
